swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error




  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Get a list of user accounts
      description: API for fetching the list of user accounts
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved user accounts
          schema:
            $ref: '#/definitions/AccountsResponse'
        '400':
          description: Bad Request - Invalid Parameters
        '401':
          description: Unauthorized - Invalid or Missing Authorization Token
        '403':
          description: Forbidden - Access Denied
        '500':
          description: Internal Server Error

  /user/accounts/{accountid}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Get transactions of a user account
      description: API for fetching the transactions of a specific user account
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountid
          description: Account ID
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved transactions
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Bad Request - Invalid Parameters
        '401':
          description: Unauthorized - Invalid or Missing Authorization Token
        '403':
          description: Forbidden - Access Denied
        '404':
          description: Not Found - Account Not Found
        '500':
          description: Internal Server Error

  /user/accounts/{accountid}/transactions/{transactionid}:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Retrieve a specific transaction
      description: API for retrieving details of a specific transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountid
          description: Account ID
          required: true
        - in: path
          type: string
          name: transactionid
          description: Transaction ID
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema: 
            $ref: '#/definitions/TransactionUpdatedResponse'
        '400':
          description: Bad Request - Invalid Parameters
        '401':
          description: Unauthorized - Invalid or Missing Authorization Token
        '403':
          description: Forbidden - Access Denied
        '404':
          description: Not Found - Transaction Not Found
        '500':
          description: Internal Server Error
          

    put:
      security:
        - Bearer: []
      tags:
        - Accounts Module
      summary: Update a specific transaction
      description: API for updating a specific transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: accountid
          description: Account ID
          required: true
        - in: path
          type: string
          name: transactionid
          description: Transaction ID
          required: true
        - in: body
          name: body
          description: Payload for updating transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionUpdatedResponse'
        '400':
          description: Invalid Fields - Incorrect or Missing Fields in Request Body
        '401':
          description: Unauthorized - Invalid or Missing Authorization Token
        '403':
          description: Forbidden - Access Denied
        '404':
          description: Not Found - Transaction or Account Not Found
        '500':
          description: Internal Server Error








securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
        
        
  AccountsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Account'

  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
      notes:
        type: string

  TransactionUpdatedResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: '#/definitions/Transaction'

  Account:
    type: object
    properties:
      accountId:
        type: string
        description: The ID of the account
      title:
        type: string
        description: The title or name of the account
      balance:
        type: string
        description: The current balance of the account
      currency:
        type: string
        description: The currency type of the account

  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: The ID of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: string
        description: Amount of the transaction
      currency:
        type: string
        description: Currency type of the transaction
      balance:
        type: string
        description: The balance after the transaction
      date:
        type: string
        format: date
        description: The date of the transaction
      type:
        type: string
        description: The type of transaction
      category:
        type: string
        description: The category of the transaction
      notes:
        type: string
        description: Additional notes regarding the transaction     
        
        